import { BeaconDefinition, BeaconColor } from './types';

export const BEACON_DEFINITIONS: Record<BeaconColor, BeaconDefinition> = {
  rainbow: {
    color: 'rainbow',
    label: 'Rainbow',
    rarity: 'rare',
    maxCount: -1,
    baseEffect: 'Vibrant for 10 challenges',
    vibrantEffect: 'Vibrant for 20 challenges',
    vibrantAquaEffect: 'Vibrant for 60 challenges',
    emoji: '🌈',
    colorHex: '#ff6b6b',
    glowColor: 'rgba(255, 107, 107, 0.6)',
  },
  orange: {
    color: 'orange',
    label: 'Orange',
    rarity: 'medium',
    maxCount: -1,
    baseEffect: '+5 beacon choices',
    vibrantEffect: '+10 beacon choices',
    vibrantAquaEffect: '+30 beacon choices',
    emoji: '🟠',
    colorHex: '#ff9f43',
    glowColor: 'rgba(255, 159, 67, 0.6)',
  },
  aqua: {
    color: 'aqua',
    label: 'Aqua',
    rarity: 'common',
    maxCount: -1,
    baseEffect: 'Boosts next beacon by 100%',
    vibrantEffect: 'Boosts next beacon by 200%',
    vibrantAquaEffect: 'Boosts next beacon by 200% (same as vibrant)',
    emoji: '💧',
    colorHex: '#00d2d3',
    glowColor: 'rgba(0, 210, 211, 0.6)',
  },
  blue: {
    color: 'blue',
    label: 'Blue',
    rarity: 'common',
    maxCount: -1,
    baseEffect: '4 boon choices at 100% potency',
    vibrantEffect: '4 boon choices at 200% potency',
    vibrantAquaEffect: '4 boon choices at 600% potency',
    emoji: '🔵',
    colorHex: '#54a0ff',
    glowColor: 'rgba(84, 160, 255, 0.6)',
  },
  purple: {
    color: 'purple',
    label: 'Purple',
    rarity: 'common',
    maxCount: -1,
    baseEffect: '+1 curse, +1 pull',
    vibrantEffect: '+2 curses, +2 pulls',
    vibrantAquaEffect: '+6 curses, +6 pulls',
    emoji: '🟣',
    colorHex: '#a855f7',
    glowColor: 'rgba(168, 85, 247, 0.6)',
  },
  yellow: {
    color: 'yellow',
    label: 'Yellow',
    rarity: 'common',
    maxCount: -1,
    baseEffect: 'Spawns 1 flying chest',
    vibrantEffect: 'Spawns 2 flying chests',
    vibrantAquaEffect: 'Spawns 6 flying chests',
    emoji: '🟡',
    colorHex: '#feca57',
    glowColor: 'rgba(254, 202, 87, 0.6)',
  },
  green: {
    color: 'green',
    label: 'Green',
    rarity: 'common',
    maxCount: -1,
    baseEffect: '+120s, mobs gain no buffs for 1 challenge',
    vibrantEffect: '+240s, mobs gain no buffs for 2 challenges',
    vibrantAquaEffect: '+720s, mobs gain no buffs for 3 challenges',
    emoji: '🟢',
    colorHex: '#2ecc71',
    glowColor: 'rgba(46, 204, 113, 0.6)',
  },
  white: {
    color: 'white',
    label: 'White',
    rarity: 'rare',
    maxCount: 1,
    baseEffect: '+5 challenges with time',
    vibrantEffect: '+10 challenges with time',
    vibrantAquaEffect: '+30 challenges with time',
    emoji: '⚪',
    colorHex: '#f0f0f0',
    glowColor: 'rgba(240, 240, 240, 0.5)',
  },
  red: {
    color: 'red',
    label: 'Red',
    rarity: 'common',
    maxCount: -1,
    baseEffect: '+3 challenges (no time)',
    vibrantEffect: '+5 challenges (no time)',
    vibrantAquaEffect: '+15 challenges (no time)',
    emoji: '🔴',
    colorHex: '#ee5a24',
    glowColor: 'rgba(238, 90, 36, 0.6)',
  },
  pink: {
    color: 'pink',
    label: 'Pink',
    rarity: 'medium',
    maxCount: -1,
    baseEffect: '+1 beacon reroll',
    vibrantEffect: '+2 beacon rerolls',
    vibrantAquaEffect: '+6 beacon rerolls',
    emoji: '🩷',
    colorHex: '#ff6b9d',
    glowColor: 'rgba(255, 107, 157, 0.6)',
  },
  gray: {
    color: 'gray',
    label: 'Gray',
    rarity: 'common',
    maxCount: 3,
    baseEffect: '3 mission choices',
    vibrantEffect: '4 mission choices',
    vibrantAquaEffect: '5 mission choices',
    emoji: '🔘',
    colorHex: '#95a5a6',
    glowColor: 'rgba(149, 165, 166, 0.5)',
  },
  darkGray: {
    color: 'darkGray',
    label: 'Dark Gray',
    rarity: 'rare',
    maxCount: 1,
    baseEffect: '+3 curses, +3 pulls',
    vibrantEffect: '+6 curses, +6 pulls',
    vibrantAquaEffect: '+18 curses, +18 pulls',
    emoji: '⚫',
    colorHex: '#636e72',
    glowColor: 'rgba(99, 110, 114, 0.5)',
  },
  crimson: {
    color: 'crimson',
    label: 'Crimson',
    rarity: 'medium',
    maxCount: 2,
    baseEffect: '2 trial choices',
    vibrantEffect: '3 trial choices',
    vibrantAquaEffect: '4 trial choices',
    emoji: '🔻',
    colorHex: '#c0392b',
    glowColor: 'rgba(192, 57, 43, 0.6)',
  },
};

export const BEACON_COLORS: BeaconColor[] = [
  'rainbow', 'orange', 'aqua', 'blue', 'purple',
  'yellow', 'green', 'white', 'red', 'pink',
  'gray', 'darkGray', 'crimson',
];
