import { MissionName, MissionObjectiveType } from './types';

export interface MissionDefinition {
  name: MissionName;
  label: string;
  description: string;
  type: 'pull_farming' | 'chest_farming' | 'survival' | 'qol' | 'beacon_manipulation' | 'run_extension' | 'reroll' | 'sacrifice';
  comboRole: 'required' | 'recommended' | 'side' | 'standalone';
  compatibleCombos: string[];
  objectiveType: MissionObjectiveType;
  objectiveTarget: number;
  objectiveLabel: string;
}

export function createMissionObjective(def: MissionDefinition) {
  return {
    type: def.objectiveType,
    target: def.objectiveTarget,
    current: 0,
    label: def.objectiveLabel,
  };
}

export const MISSION_DEFINITIONS: Record<MissionName, MissionDefinition> = {
  cleansing_greed: {
    name: 'cleansing_greed',
    label: 'Cleansing Greed',
    description: 'After opening a Flying Chest, remove one of your Curses.',
    type: 'qol',
    comboRole: 'side',
    compatibleCombos: ['opal_offering', 'jesters_scheme'],
    objectiveType: 'open_chests',
    objectiveTarget: 5,
    objectiveLabel: 'Open 5 Flying Chests',
  },
  materialism: {
    name: 'materialism',
    label: 'Materialism',
    description: 'Spawns 2 flying chests after every challenge completed.',
    type: 'chest_farming',
    comboRole: 'recommended',
    compatibleCombos: ['jesters_scheme'],
    objectiveType: 'complete_challenges',
    objectiveTarget: 8,
    objectiveLabel: 'Complete 8 challenges',
  },
  hoarder: {
    name: 'hoarder',
    label: 'Hoarder',
    description: 'After opening 7 chests, choose 1 boon at 100% potency from 3 options.',
    type: 'qol',
    comboRole: 'side',
    compatibleCombos: ['jesters_scheme'],
    objectiveType: 'open_chests',
    objectiveTarget: 7,
    objectiveLabel: 'Open 7 chests',
  },
  jesters_trick: {
    name: 'jesters_trick',
    label: "Jester's Trick",
    description: 'After being offered 30 items from Flying Chests, randomly get +3 Pulls, +1 Boon, +1 Curse, or +30s.',
    type: 'qol',
    comboRole: 'required',
    compatibleCombos: ['jesters_scheme'],
    objectiveType: 'open_chests',
    objectiveTarget: 30,
    objectiveLabel: 'Be offered 30 items from chests',
  },
  interest_scheme: {
    name: 'interest_scheme',
    label: 'Interest Scheme',
    description: 'Gaining 2 pulls adds an additional Flying Chest to your next Yellow Beacon. (Max 12)',
    type: 'chest_farming',
    comboRole: 'required',
    compatibleCombos: ['jesters_scheme'],
    objectiveType: 'gain_pulls',
    objectiveTarget: 6,
    objectiveLabel: 'Gain 6 pulls',
  },
  orphions_grace: {
    name: 'orphions_grace',
    label: "Orphion's Grace",
    description: 'Boons are now 50% more effective.',
    type: 'qol',
    comboRole: 'side',
    compatibleCombos: ['jesters_scheme', 'opal_offering'],
    objectiveType: 'obtain_boons',
    objectiveTarget: 3,
    objectiveLabel: 'Obtain 3 boons',
  },
  opal_offering: {
    name: 'opal_offering',
    label: 'Opal Offering',
    description: 'After obtaining a curse, consume 1 Boon to gain +3 Pulls (+1 per 50% Potency).',
    type: 'pull_farming',
    comboRole: 'required',
    compatibleCombos: ['opal_offering'],
    objectiveType: 'gain_curses',
    objectiveTarget: 3,
    objectiveLabel: 'Obtain 3 curses',
  },
  gourmand: {
    name: 'gourmand',
    label: 'Gourmand',
    description: 'Gain 1 beacon choice for this challenge for every beacon reroll used. (Cap 6)',
    type: 'beacon_manipulation',
    comboRole: 'side',
    compatibleCombos: ['gambling_beast'],
    objectiveType: 'use_rerolls',
    objectiveTarget: 3,
    objectiveLabel: 'Use 3 beacon rerolls',
  },
  porphyrophobia: {
    name: 'porphyrophobia',
    label: 'Porphyrophobia',
    description: 'Getting offered a Purple Beacon gives +1 Curse. Purple Beacons now give twice as many Pulls.',
    type: 'pull_farming',
    comboRole: 'standalone',
    compatibleCombos: ['chronotrigger', 'comboless'],
    objectiveType: 'none',
    objectiveTarget: 0,
    objectiveLabel: 'No objective — passive effect',
  },
  sacrificial_ritual: {
    name: 'sacrificial_ritual',
    label: 'Sacrificial Ritual',
    description: 'After finishing a Challenge, consume 1 Pull to gain +3 Challenges.',
    type: 'run_extension',
    comboRole: 'recommended',
    compatibleCombos: ['opal_offering', 'jesters_scheme', 'gambling_beast'],
    objectiveType: 'gain_pulls',
    objectiveTarget: 5,
    objectiveLabel: 'Gain 5 pulls',
  },
  equilibrium: {
    name: 'equilibrium',
    label: 'Equilibrium',
    description: 'Getting a curse adds +50% Potency to your next Boon. (Capped at +300%)',
    type: 'qol',
    comboRole: 'standalone',
    compatibleCombos: ['chronotrigger'],
    objectiveType: 'gain_curses',
    objectiveTarget: 3,
    objectiveLabel: 'Obtain 3 curses',
  },
  inner_peace: {
    name: 'inner_peace',
    label: 'Inner Peace',
    description: 'Curses are now half as effective.',
    type: 'survival',
    comboRole: 'standalone',
    compatibleCombos: ['comboless', 'chronotrigger'],
    objectiveType: 'gain_curses',
    objectiveTarget: 4,
    objectiveLabel: 'Obtain 4 curses',
  },
  radiant_hunter: {
    name: 'radiant_hunter',
    label: 'Radiant Hunter',
    description: 'Killing a Radiant challenge mob grants +1 Pull. (Max +5 Pulls per challenge)',
    type: 'pull_farming',
    comboRole: 'recommended',
    compatibleCombos: ['opal_offering', 'jesters_scheme', 'chronotrigger', 'comboless'],
    objectiveType: 'complete_challenges',
    objectiveTarget: 5,
    objectiveLabel: 'Complete 5 challenges with Radiant mobs',
  },
  optimism: {
    name: 'optimism',
    label: 'Optimism',
    description: 'Upon rerolling a beacon, it will not be re-offered until no more beacons can be offered.',
    type: 'beacon_manipulation',
    comboRole: 'side',
    compatibleCombos: ['gambling_beast'],
    objectiveType: 'use_rerolls',
    objectiveTarget: 5,
    objectiveLabel: 'Use 5 beacon rerolls',
  },
  backup_beat: {
    name: 'backup_beat',
    label: 'Backup Beat',
    description: 'Every time you add +300s to your timer, gain +1 Beacon Reroll.',
    type: 'reroll',
    comboRole: 'side',
    compatibleCombos: ['gambling_beast'],
    objectiveType: 'add_time',
    objectiveTarget: 300,
    objectiveLabel: 'Add 300s to timer',
  },
  stasis: {
    name: 'stasis',
    label: 'Stasis',
    description: 'While picking a Beacon, your timer does not decrease. (Max 5 minutes)',
    type: 'qol',
    comboRole: 'standalone',
    compatibleCombos: [],
    objectiveType: 'complete_challenges',
    objectiveTarget: 6,
    objectiveLabel: 'Complete 6 challenges',
  },
  chronokinesis: {
    name: 'chronokinesis',
    label: 'Chronokinesis',
    description: 'Chests now give +1 Pull, but consume 10s (+5s per chest) from your Timer. Completing a challenge reduces this penalty by -15s.',
    type: 'pull_farming',
    comboRole: 'side',
    compatibleCombos: ['jesters_scheme', 'chronotrigger', 'comboless'],
    objectiveType: 'open_chests',
    objectiveTarget: 10,
    objectiveLabel: 'Open 10 chests',
  },
  requiem: {
    name: 'requiem',
    label: 'Requiem',
    description: 'For the next 15 minutes, mob stat increases are voided. Includes passive enemy buffs and any curses.',
    type: 'survival',
    comboRole: 'standalone',
    compatibleCombos: [],
    objectiveType: 'complete_challenges',
    objectiveTarget: 5,
    objectiveLabel: 'Complete 5 challenges',
  },
  thrill_seeker: {
    name: 'thrill_seeker',
    label: 'Thrill Seeker',
    description: 'Red Beacons will reward 1 Boon out of 5.',
    type: 'qol',
    comboRole: 'standalone',
    compatibleCombos: [],
    objectiveType: 'none',
    objectiveTarget: 0,
    objectiveLabel: 'No objective — passive effect',
  },
  high_roller: {
    name: 'high_roller',
    label: 'High Roller',
    description: 'Gain +10 Pulls and +1 End Reward Reroll.',
    type: 'pull_farming',
    comboRole: 'side',
    compatibleCombos: ['opal_offering', 'jesters_scheme', 'gambling_beast', 'comboless'],
    objectiveType: 'none',
    objectiveTarget: 0,
    objectiveLabel: 'No objective — instant effect',
  },
  redemption: {
    name: 'redemption',
    label: 'Redemption',
    description: 'Gain +1 End Reward Sacrifice.',
    type: 'sacrifice',
    comboRole: 'side',
    compatibleCombos: ['opal_offering', 'jesters_scheme', 'gambling_beast', 'comboless'],
    objectiveType: 'none',
    objectiveTarget: 0,
    objectiveLabel: 'No objective — instant effect',
  },
  complete_chaos: {
    name: 'complete_chaos',
    label: 'Complete Chaos',
    description: 'After finishing a Challenge, get an additional random Beacon reward.',
    type: 'qol',
    comboRole: 'side',
    compatibleCombos: ['jesters_scheme'],
    objectiveType: 'complete_challenges',
    objectiveTarget: 5,
    objectiveLabel: 'Complete 5 challenges',
  },
};
