import { MissionName } from './types';

export interface MissionDefinition {
  name: MissionName;
  label: string;
  description: string;
  type: 'pull_farming' | 'chest_farming' | 'survival' | 'qol' | 'beacon_manipulation' | 'run_extension' | 'reroll' | 'sacrifice';
  comboRole: 'required' | 'recommended' | 'side' | 'standalone';
  compatibleCombos: string[];
}

export const MISSION_DEFINITIONS: Record<MissionName, MissionDefinition> = {
  cleansing_greed: {
    name: 'cleansing_greed',
    label: 'Cleansing Greed',
    description: 'After opening a Flying Chest, remove one of your Curses.',
    type: 'qol',
    comboRole: 'side',
    compatibleCombos: ['opal_offering', 'jesters_scheme'],
  },
  materialism: {
    name: 'materialism',
    label: 'Materialism',
    description: 'Spawns 2 flying chests after every challenge completed.',
    type: 'chest_farming',
    comboRole: 'recommended',
    compatibleCombos: ['jesters_scheme'],
  },
  hoarder: {
    name: 'hoarder',
    label: 'Hoarder',
    description: 'After opening 7 chests, choose 1 boon at 100% potency from 3 options.',
    type: 'qol',
    comboRole: 'side',
    compatibleCombos: ['jesters_scheme'],
  },
  jesters_trick: {
    name: 'jesters_trick',
    label: "Jester's Trick",
    description: 'After being offered 30 items from Flying Chests, randomly get +3 Pulls, +1 Boon, +1 Curse, or +30s.',
    type: 'qol',
    comboRole: 'required',
    compatibleCombos: ['jesters_scheme'],
  },
  interest_scheme: {
    name: 'interest_scheme',
    label: 'Interest Scheme',
    description: 'Gaining 2 pulls adds an additional Flying Chest to your next Yellow Beacon. (Max 12)',
    type: 'chest_farming',
    comboRole: 'required',
    compatibleCombos: ['jesters_scheme'],
  },
  orphions_grace: {
    name: 'orphions_grace',
    label: "Orphion's Grace",
    description: 'Boons are now 50% more effective.',
    type: 'qol',
    comboRole: 'side',
    compatibleCombos: ['jesters_scheme', 'opal_offering'],
  },
  opal_offering: {
    name: 'opal_offering',
    label: 'Opal Offering',
    description: 'After obtaining a curse, consume 1 Boon to gain +3 Pulls (+1 per 50% Potency).',
    type: 'pull_farming',
    comboRole: 'required',
    compatibleCombos: ['opal_offering'],
  },
  gourmand: {
    name: 'gourmand',
    label: 'Gourmand',
    description: 'Gain 1 beacon choice for this challenge for every beacon reroll used. (Cap 6)',
    type: 'beacon_manipulation',
    comboRole: 'side',
    compatibleCombos: ['gambling_beast'],
  },
  porphyrophobia: {
    name: 'porphyrophobia',
    label: 'Porphyrophobia',
    description: 'Getting offered a Purple Beacon gives +1 Curse. Purple Beacons now give twice as many Pulls.',
    type: 'pull_farming',
    comboRole: 'standalone',
    compatibleCombos: ['chronotrigger', 'comboless'],
  },
  sacrificial_ritual: {
    name: 'sacrificial_ritual',
    label: 'Sacrificial Ritual',
    description: 'After finishing a Challenge, consume 1 Pull to gain +3 Challenges.',
    type: 'run_extension',
    comboRole: 'recommended',
    compatibleCombos: ['opal_offering', 'jesters_scheme', 'gambling_beast'],
  },
  equilibrium: {
    name: 'equilibrium',
    label: 'Equilibrium',
    description: 'Getting a curse adds +50% Potency to your next Boon. (Capped at +300%)',
    type: 'qol',
    comboRole: 'standalone',
    compatibleCombos: ['chronotrigger'],
  },
  inner_peace: {
    name: 'inner_peace',
    label: 'Inner Peace',
    description: 'Curses are now half as effective.',
    type: 'survival',
    comboRole: 'standalone',
    compatibleCombos: ['comboless', 'chronotrigger'],
  },
  radiant_hunter: {
    name: 'radiant_hunter',
    label: 'Radiant Hunter',
    description: 'Killing a Radiant challenge mob grants +1 Pull. (Max +5 Pulls per challenge)',
    type: 'pull_farming',
    comboRole: 'recommended',
    compatibleCombos: ['opal_offering', 'jesters_scheme', 'chronotrigger', 'comboless'],
  },
  optimism: {
    name: 'optimism',
    label: 'Optimism',
    description: 'Upon rerolling a beacon, it will not be re-offered until no more beacons can be offered.',
    type: 'beacon_manipulation',
    comboRole: 'side',
    compatibleCombos: ['gambling_beast'],
  },
  backup_beat: {
    name: 'backup_beat',
    label: 'Backup Beat',
    description: 'Every time you add +300s to your timer, gain +1 Beacon Reroll.',
    type: 'reroll',
    comboRole: 'side',
    compatibleCombos: ['gambling_beast'],
  },
  stasis: {
    name: 'stasis',
    label: 'Stasis',
    description: 'While picking a Beacon, your timer does not decrease. (Max 5 minutes)',
    type: 'qol',
    comboRole: 'standalone',
    compatibleCombos: [],
  },
  chronokinesis: {
    name: 'chronokinesis',
    label: 'Chronokinesis',
    description: 'Chests now give +1 Pull, but consume 10s (+5s per chest) from your Timer. Completing a challenge reduces this penalty by -15s.',
    type: 'pull_farming',
    comboRole: 'side',
    compatibleCombos: ['jesters_scheme', 'chronotrigger', 'comboless'],
  },
  requiem: {
    name: 'requiem',
    label: 'Requiem',
    description: 'For the next 15 minutes, mob stat increases are voided. Includes passive enemy buffs and any curses.',
    type: 'survival',
    comboRole: 'standalone',
    compatibleCombos: [],
  },
  thrill_seeker: {
    name: 'thrill_seeker',
    label: 'Thrill Seeker',
    description: 'Red Beacons will reward 1 Boon out of 5.',
    type: 'qol',
    comboRole: 'standalone',
    compatibleCombos: [],
  },
  high_roller: {
    name: 'high_roller',
    label: 'High Roller',
    description: 'Gain +10 Pulls and +1 End Reward Reroll.',
    type: 'pull_farming',
    comboRole: 'side',
    compatibleCombos: ['opal_offering', 'jesters_scheme', 'gambling_beast', 'comboless'],
  },
  redemption: {
    name: 'redemption',
    label: 'Redemption',
    description: 'Gain +1 End Reward Sacrifice.',
    type: 'sacrifice',
    comboRole: 'side',
    compatibleCombos: ['opal_offering', 'jesters_scheme', 'gambling_beast', 'comboless'],
  },
  complete_chaos: {
    name: 'complete_chaos',
    label: 'Complete Chaos',
    description: 'After finishing a Challenge, get an additional random Beacon reward.',
    type: 'qol',
    comboRole: 'side',
    compatibleCombos: ['jesters_scheme'],
  },
};
